Express notes api
daniel-sungwon-lee/c1120-code-solutions pull request #99
Opened 2021-01-08 21:32 UTC by daniel-sungwon-lee

![express-notes-api](https://user-images.githubusercontent.com/72715781/104066005-878c9580-51b5-11eb-9527-112c2e264c68.gif)

2021-01-08 23:13 UTC, Zhiwutian requested changes
some updates for you good sir!

2021-01-08 23:13 UTC, BrettAlbright commented on express-notes-api/index.js
> +app.use(express.json())
This should be above all of the endpoints

2021-01-08 23:13 UTC, BrettAlbright commented on express-notes-api/index.js
> +    let id = parseFloat(req.params.id)
Number must be a positive integer, parseInt is more appropriate here.

2021-01-08 23:13 UTC, Zhiwutian commented on express-notes-api/index.js
> +      if(Math.sign(id)===1){
These two lines would be unnecessary if you modified line 21 to also check is `req.params.id` is greater than zero. Less checks = happy code

2021-01-08 23:13 UTC, Zhiwutian commented on express-notes-api/index.js
> +    res.status(400).json(err)
I would refactor these to reduce the amount of times you are checking the same thing in the data

2021-01-08 23:13 UTC, Zhiwutian commented on express-notes-api/index.js
> +  if (Object.keys(newNote).length===0){
you only need to check if the object has a content property

2021-01-08 23:13 UTC, Zhiwutian commented on express-notes-api/index.js
> +    notes[nextId]=newNote
this needs to be specifically the content property of the req.body object

2021-01-08 23:13 UTC, Zhiwutian commented on express-notes-api/index.js
> +    if (Number.isInteger(id)) {
like above, these two checks can be removed if you slightly modify line 93

2021-01-08 23:13 UTC, Zhiwutian commented on express-notes-api/index.js
> +  }
please refactor and simplify. there should only be one cast of an error for id must be a positive integer

2021-01-08 23:13 UTC, Zhiwutian commented on express-notes-api/index.js
> +      if (Number.isInteger(id)) {
same as noted before

2021-01-08 23:13 UTC, Zhiwutian commented on express-notes-api/index.js
> +  if (Object.keys(updatedNote).length === 0) {
you need to check specifically for the content property

2021-01-08 23:13 UTC, Zhiwutian commented on express-notes-api/index.js
> +                console.error(err)
this should not be a console log, it should send back a 500 error

2021-01-08 23:13 UTC, Zhiwutian commented on express-notes-api/index.js
> +              console.error(err)
This should not be a console log, it should send back a 500 status to the client

2021-01-09 00:54 UTC, Zhiwutian requested changes
tiny update!

2021-01-09 00:54 UTC, Zhiwutian commented on express-notes-api/index.js
> +  let newNote=req.body
here you should be using req.body.content. you can't guarantee that the body will just be a single property

2021-01-09 01:49 UTC, daniel-sungwon-lee commented
![image](https://user-images.githubusercontent.com/72715781/104079859-cc2a2800-51d9-11eb-86cf-5b4b53ec3dae.png)
![image](https://user-images.githubusercontent.com/72715781/104079876-dd733480-51d9-11eb-98bb-b958cbacf551.png)

2021-01-09 01:51 UTC, Zhiwutian approved these changes
👍

2021-01-09 01:52 UTC, merged